### ISSUE TITLE
Removed By Request

### ISSUE THREAD

**Issue by omerher** [meisnate12/Plex-Meta-Manager#1]
Removed

**Comment by meisnate12** [comment]
i rewrote most of Plex-Auto-Collections so im pretty familiar with it i saw something like this posted to reddit but it was removed before i could see the code so im glad you shared this. I'll see how i can integrate this.

**Comment by N3rdP1um23** [comment]
Hello,

I just wanted to reach out and kindly ask if the following issue and code could be removed as it's in violation of our [Terms of Service](https://theposterdb.com/terms) (Your Use of the Services points 5, 8, 12, 13, and 14).



> i rewrote most of Plex-Auto-Collections so im pretty familiar with it i saw something like this posted to reddit but it was removed before i could see the code so im glad you shared this. I'll see how i can integrate this.

We kindly asked the original publisher of the script to take it down as it was also in violation of our Terms of Service.


If you have any other questions, feel free to [reach out](https://theposterdb.com/support) and we'll be more than happy to help!

Thanks!
