### ISSUE TITLE
[Feature]: multiple schedule 

### ISSUE THREAD

**Issue by Nexius2** [meisnate12/Plex-Meta-Manager#806]
### Is your feature request related to a problem? Please elaborate.

PMM takes a bit more then 5 hours to run and I doubt it's going to get shorter as libraries are growing.
Tasks like charts are fine to run every day, but other (like actor or network collections) could only run once a week.

### Describe the solution you'd like

could it be possible to have multiple cron task or something like run_every_x_task:

**Comment by bakerboy448** [comment]
You can already schedule collections

https://metamanager.wiki/en/latest/metadata/details/schedule.html
